### PR TITLE
ci: add Linux aarch64 and ppc64le builds

### LINKED ISSUE #1: Add Linux aarch64 and ppc64le builds
@Saransh-cpp Can you try to add aarch64 and ppc64le builds by adding the following to `conda-forge.yml` in a PR from your personal fork of this feedstock

```yaml
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
```

(c.f. https://conda-forge.org/docs/maintainer/conda_forge_yml/#build-platform) and then in the PR rerender with `@conda-forge-admin, please rerender` (and bump the build number)?

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #1

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
@conda-forge-admin, please rerender

**Comment by Saransh-cpp** [comment]
@conda-forge-admin, please rerender

**Comment by Saransh-cpp** [comment]
Tagging @matthewfeickert for a review here! 🙂

**Review by matthewfeickert — APPROVED** [review]
LGTM. Feel free to squash and merge. :+1:

**Pull request merged**
